apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: sample-app
          image: 153889942928.dkr.ecr.ap-southeast-2.amazonaws.com/sample-app:1.0.0
          resources:
            limits:
              memory: 1250Mi
            requests:
              memory: 1250Mi
