apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: sample-app
          image: rajeshgpai/sample-app:0.0.1-SNAPSHOT
          resources:
            limits:
              memory: 1250Mi
            requests:
              memory: 1250Mi
